baseURL = 'http://blog.911015.com/'
languageCode = 'en-us'
title = 'Go语言入门'
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = true # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
  definitionList = true
  footnote = true
  linkify = true
  linkifyProtocol = 'https'
  strikethrough = true
  table = true
  taskList = true
  typographer = true
[markup.goldmark.parser]
  autoHeadingID = true
  autoHeadingIDType = 'github'
  wrapStandAloneImageWithinParagraph = true
  [markup.goldmark.parser.attribute]
    block = false
    title = true
[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xhtml = false

[outputs]
home = [ "HTML"]