baseURL = 'http://blog.911015.com/'
languageCode = 'en-us'
title = 'Go语言入门'
theme = "ace"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
sectionPagesMenu = 'main'
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
enableRobotsTXT = true

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableFavorites = true
site_icp = "鲁ICP备17023316号-1"
site_logo = "/img/site_logo.png"
[markup]
[markup.goldmark]
[markup.goldmark.extensions]
  definitionList = true
  footnote = true
  linkify = true
  linkifyProtocol = 'https'
  strikethrough = true
  table = true
  taskList = true
  typographer = true
[markup.goldmark.parser]
  autoHeadingID = true
  autoHeadingIDType = 'github'
  wrapStandAloneImageWithinParagraph = true
  [markup.goldmark.parser.attribute]
    block = false
    title = true
[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xhtml = false

[outputs]
home = ["HTML","RSS","JSON"]
[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[menu]
[[menu.shortcuts]]
name = "<i class='fab fa-qq'></i> QQ"
url = "/contact.html"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/LittleMoreInteresting/beginner-example"
weight = 2

[[params.cards]]
name = "<i class='far fa-hand-point-right'></i>关注公众号领取Go学习资料"
img = "/img/qrcode_for_gh_3982836909ff_258.jpg"
url = "/contact.html"
weight = 1

[[params.cards]]
name = "<i class='far fa-hand-point-right'></i>洋葱小店<i class='far fa-hand-point-left'></i>"
img = "/img/jd.jpg"
url = "https://m.msyc.cc/wx/index.html?tmn=58654"
weight = 2

[[params.cards]]
name = "<i class='far fa-hand-point-right'></i>LUCA<i class='far fa-hand-point-left'></i>"
img = "/img/tb.jpg"
url = "https://m.msyc.cc/wx/lucaBrand.html?tmn=58654&shared_id=906513"
weight = 2
